### ISSUE TITLE
add-admin needs some work, firstname and lastname does not go to the database, there is no redirect

### ISSUE THREAD

**Issue by bartvdklu** [de-sigaar/ikwil-dashboard#44]

**Comment by MariusHendriks** [comment]
Dit is een probleem voor @MaxAltena in de cloud functions

**Comment by MaxAltena** [comment]
Shall take a look at it for you

**Comment by MaxAltena** [comment]
Fixed it in https://github.com/de-sigaar/stichting-ik-wil/commit/93724c73d89b82b77465c1538d245d8602af0dd3
